# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the warkop branch
  push:
    branches: [ warkop ]
  pull_request:
    branches: [ warkop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        env:
          USER: root
        with:
          apiToken: TeJ4iG8i1WUXdKHnc90BmmpEPHHYSC8Bstu1oIy-
